#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# PostHog setup for parterre (#259, decided on #225): scripts/posthog-setup.sh
#
# Walks the maintainer through PostHog's web UI: the EU account, the organisation and the
# parterre project, the DPA, the IP and GeoIP settings, billing, the project token for the app
# (#261), the personal API key for symbol upload (#265) as GitHub Actions secrets, and the first
# insight. Every step can be skipped; a re-run offers only the steps not done yet.
#
# Progress and the public values (project token and ID) are kept in
# ~/.local/state/parterre/posthog-setup.env ($PARTERRE_POSTHOG_STATE overrides it). The
# personal API key is never printed or written to disk: it goes from hidden input to PostHog's
# API (to check it, if you agree) and to `gh secret set` on stdin.

TOTAL_STAGES=8
TOTAL_MINUTES=30

POSTHOG=https://eu.posthog.com
export GH_REPO=aquamoth/parterre
ENV_FILE="${PARTERRE_POSTHOG_STATE:-${XDG_STATE_HOME:-$HOME/.local/state}/parterre/posthog-setup.env}"
mkdir -p "$(dirname "$ENV_FILE")"

# is_done KEY — whether the step KEY was finished on an earlier run.
is_done() { [[ "$(_existing "DONE_$1" || true)" == 1 ]]; }

# mark_done KEY — remember that the step KEY is finished.
mark_done() {
  local tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^DONE_$1=" "$ENV_FILE" > "$tmp" || true
  printf 'DONE_%s=1\n' "$1" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
}

# begin_step KEY "Title" <minutes> "What it is" — show the step; succeed if the human does it
# now. A finished step is passed over with Enter; an unfinished one can be put off with s.
begin_step() {
  local reply=""
  stage "$2" "$3"
  say "$4"
  printf '\n'
  if is_done "$1"; then
    note "Done on an earlier run."
    printf '  %sEnter skips it, r does it again:%s ' "$DIM" "$RESET"
    read -r reply || true
    [[ "$reply" =~ ^[Rr] ]] || return 1
  else
    printf '  %sEnter starts it, s skips it for now:%s ' "$DIM" "$RESET"
    read -r reply || true
    if [[ "$reply" =~ ^[Ss] ]]; then
      SKIPPED+=("$2 (run the wizard again to do it)")
      return 1
    fi
  fi
  printf '\n'
}

# end_step KEY "Title" — ask whether the step is finished, and remember it if so.
end_step() {
  printf '\n'
  if confirm "Is this step finished?"; then
    mark_done "$1"
  else
    SKIPPED+=("$2 (run the wizard again to finish it)")
  fi
}

# ask_matching KEY "Prompt" REGEX "Hint" — ask until the answer matches.
ask_matching() {
  while :; do
    ask "$1" "$2"
    [[ "${!1}" =~ $3 ]] && return
    warn "$4 Try again."
  done
}

# posthog_get PATH — GET $POSTHOG/api/PATH with the personal API key, which reaches curl on
# stdin, not on its command line. Prints the body, then the HTTP status on a line of its own.
posthog_get() {
  printf 'Authorization: Bearer %s\n' "$PERSONAL_KEY" |
    curl -sS --max-time 20 -H @- -w '\n%{http_code}' "$POSTHOG/api/$1" 2>/dev/null ||
    printf '\n000'
}

banner "PostHog for parterre"

# ── 1. Account ────────────────────────────────────────────────────────────
if begin_step SIGNUP "Account in PostHog's EU region" 5 \
  "A PostHog account in the EU region (Frankfurt), where parterre's data is kept."; then
  warn "The region is chosen at sign-up. Moving to the other one later means migrating"
  warn "the data, so check that it says European Union before you sign up."
  open_url "$POSTHOG/signup"
  step "Check that the 'Data region' field says 'European Union'."
  step "Sign up with your email (or one of the sign-in buttons)."
  step "The next page asks 'Your name' and 'Organization name': the organisation is"
  say  "  Trustfall AB. The role and how-you-heard questions are up to you."
  step "PostHog may then start an onboarding (pick products, install an SDK). parterre"
  say  "  doesn't need it: skip it however the page offers."
  printf '\n'
  ask APP_URL "Once you're in, paste the address from the browser's address bar:"
  case "$APP_URL" in
    https://eu.posthog.com/* | eu.posthog.com/*)
      printf '  %s✓ EU region%s\n' "$GREEN" "$RESET"
      end_step SIGNUP "Account in PostHog's EU region"
      ;;
    *us.posthog.com* | *app.posthog.com*)
      warn "That is the US region. US and EU are separate: sign up again at $POSTHOG/signup,"
      warn "then delete the US organisation in its Settings › Organization."
      SKIPPED+=("Account in PostHog's EU region (the account is in the US region)")
      pause "Press Enter to go on."
      ;;
    *)
      warn "That isn't a PostHog address. Check that the address starts with $POSTHOG."
      end_step SIGNUP "Account in PostHog's EU region"
      ;;
  esac
fi

# ── 2. Organisation and project ───────────────────────────────────────────
if begin_step ORG_PROJECT "Organisation Trustfall AB, project parterre" 3 \
  "The organisation is Trustfall AB; its one project is named parterre."; then
  open_url "$POSTHOG/settings/organization"
  step "Under 'Name & logo', the name should be Trustfall AB. If not, change it and save."
  printf '\n'
  note "The free plan has one project, and a new organisation comes with one named"
  note "'Default Project'. Rename that one rather than making another."
  pause "Press Enter to open the project settings."
  open_url "$POSTHOG/settings/project#display-name"
  step "Under 'Project details', change the name to parterre and save."
  end_step ORG_PROJECT "Organisation Trustfall AB, project parterre"
fi

# ── 3. DPA ────────────────────────────────────────────────────────────────
if begin_step DPA "Data Processing Agreement" 5 \
  "PostHog processes data for Trustfall AB, so GDPR wants a DPA. It is self-serve and free."; then
  note "To read it first: https://posthog.com/dpa (a preview; only the copy you generate counts)."
  open_url "$POSTHOG/legal"
  step "Click '+ New', then 'Data Processing Agreement (DPA)'."
  step "Fill in the company details: legal company name Trustfall AB, and the email of"
  say  "  whoever signs. Then click 'Send for signature'."
  step "PandaDoc emails that address. Open the email and sign: PostHog has already"
  say  "  countersigned, and the DPA is in force once you sign."
  step "Keep the completed copy from the email that follows. It is also on the legal page."
  end_step DPA "Data Processing Agreement"
fi

# ── 4. IP and GeoIP ───────────────────────────────────────────────────────
if begin_step PRIVACY "Discard IP addresses, keep GeoIP" 3 \
  "Events keep the country and PostHog's other GeoIP fields, never the IP address."; then
  open_url "$POSTHOG/settings/project#datacapture"
  step "Under 'IP data capture configuration', turn 'Discard client IP data' on."
  note "EU organisations start with it on, so it is probably on already."
  note "Leave 'Cookieless server hash mode' off: it drops the IP before GeoIP can read it."
  pause "Press Enter to open the GeoIP transformation."
  open_url "$POSTHOG/data-management/transformations?search=GeoIP"
  step "PostHog adds a transformation named 'GeoIP' to new projects. Check that it is"
  say  "  listed and enabled; enable it if it isn't."
  step "If it isn't listed at all, add one from the 'GeoIP' template (look for a New or +"
  say  "  button on that page; PostHog's docs don't show it)."
  note "GeoIP reads the IP while the event is ingested, before the IP is discarded."
  end_step PRIVACY "Discard IP addresses, keep GeoIP"
fi

# ── 5. Billing ────────────────────────────────────────────────────────────
if begin_step BILLING "Billing: the free plan" 3 \
  "Stay on the free plan, without a card, so PostHog can never charge anything."; then
  say "How PostHog's billing works:"
  step "The free plan needs no card. Each product has a monthly free allowance (1M events,"
  say  "  100k exceptions); past it, PostHog stops taking that product's data until the next"
  say  "  month. Nothing is charged. It also means one project and one year of retention."
  step "Billing limits only exist once a card is added (pay-as-you-go): one per product,"
  say  "  as low as \$0. So if a card is ever added, set every product's limit at once."
  step "The organisation's owner gets an email at 80% and 100% of each free allowance."
  printf '\n'
  open_url "$POSTHOG/organization/billing"
  step "Check that the page shows the free plan and no payment card."
  step "Don't add a card or upgrade."
  end_step BILLING "Billing: the free plan"
fi

# ── 6. Project token ──────────────────────────────────────────────────────
if begin_step PROJECT_TOKEN "Project token, for the app" 2 \
  "The token parterre sends events with. It is public by design and goes in the source."; then
  open_url "$POSTHOG/settings/project#variables"
  step "Under 'Project token & ID', copy the project token (starts with phc_)."
  ask_matching POSTHOG_PROJECT_TOKEN "Paste the project token:" '^phc_[A-Za-z0-9_-]+$' \
    "A project token starts with phc_."
  step "Copy the project ID from the same place: a number, also in the address bar as"
  say  "  /project/<ID>."
  ask_matching POSTHOG_PROJECT_ID "Paste the project ID:" '^[0-9]+$' "The project ID is a number."
  write_env POSTHOG_PROJECT_TOKEN "$POSTHOG_PROJECT_TOKEN"
  write_env POSTHOG_PROJECT_ID "$POSTHOG_PROJECT_ID"
  printf '\n'
  say "Hand the token to whoever builds #261, the usage statistics: it becomes a constant"
  say "in the PostHog module of the parterre-telemetry crate."
  printf '\n  %s%s%s\n' "$BOLD" "$POSTHOG_PROJECT_TOKEN" "$RESET"
  end_step PROJECT_TOKEN "Project token, for the app"
fi

# ── 7. Personal API key, as GitHub secrets ────────────────────────────────
if begin_step CI_KEY "Personal API key for symbol upload, as GitHub secrets" 5 \
  "The release workflow uploads debug symbols with posthog-cli (#265), which needs a key."; then
  POSTHOG_PROJECT_ID=$(_existing POSTHOG_PROJECT_ID || true)
  if [[ -z "$POSTHOG_PROJECT_ID" ]]; then
    open_url "$POSTHOG/settings/project#variables"
    step "Copy the project ID under 'Project token & ID' (a number)."
    ask_matching POSTHOG_PROJECT_ID "Paste the project ID:" '^[0-9]+$' "The project ID is a number."
    write_env POSTHOG_PROJECT_ID "$POSTHOG_PROJECT_ID"
  fi
  open_url "$POSTHOG/settings/user-api-keys"
  step "Click '+ Create a personal API key'."
  step "Label: parterre release symbols."
  step "Organization & project access: 'Organizations', then Trustfall AB. (The"
  say  "  Organization scope can't be given to a key limited to projects.)"
  step "Scopes: pick the preset 'Source map upload'. It grants what PostHog's docs ask for"
  say  "  and nothing else: Error tracking write and Organization read."
  step "Create it and copy the key (starts with phx_) at once: PostHog shows it only once."
  printf '\n'
  note "The key is read hidden, sent only to PostHog and GitHub, and kept nowhere."
  PERSONAL_KEY=""
  while :; do
    ask_secret PERSONAL_KEY "Paste the personal API key:"
    [[ "$PERSONAL_KEY" =~ ^phx_[A-Za-z0-9_-]+$ ]] && break
    warn "A personal API key starts with phx_. Try again."
  done

  if command -v curl >/dev/null 2>&1 && confirm "Check the key against PostHog's API ($POSTHOG)?"; then
    reply=$(posthog_get "organizations/@current/")
    status=${reply##*$'\n'}
    if [[ "$status" == 200 ]]; then
      org=$(printf '%s' "${reply%$'\n'*}" | grep -o '"name": *"[^"]*"' | head -n1 | sed 's/.*: *"//; s/"$//' || true)
      printf '  %s✓ the key works%s in the EU region, organisation %s\n' "$GREEN" "$RESET" "${org:-?}"
    else
      warn "PostHog answered $status for the organisation: check the key, its region and"
      warn "the Organization read scope."
    fi
    reply=$(posthog_get "projects/$POSTHOG_PROJECT_ID/error_tracking/symbol_sets/?limit=1")
    status=${reply##*$'\n'}
    if [[ "$status" == 200 ]]; then
      printf '  %s✓ project %s%s and its symbol sets are reachable\n' \
        "$GREEN" "$POSTHOG_PROJECT_ID" "$RESET"
    else
      warn "PostHog answered $status for project $POSTHOG_PROJECT_ID's symbol sets: check the"
      warn "project ID and the Error tracking write scope."
    fi
  fi

  printf '\n'
  say "posthog-cli reads three variables. The release workflow sets the host,"
  say "POSTHOG_CLI_HOST=$POSTHOG, itself. The other two become secrets of"
  say "$GH_REPO, as in PostHog's own GitHub Actions example:"
  step "POSTHOG_CLI_API_KEY     the personal API key"
  step "POSTHOG_CLI_PROJECT_ID  $POSTHOG_PROJECT_ID"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    existing=$(gh secret list --json name --jq '.[].name' 2>/dev/null || true)
    for name in POSTHOG_CLI_API_KEY POSTHOG_CLI_PROJECT_ID; do
      if grep -qx "$name" <<<"$existing"; then
        note "$name is already set; setting it again replaces it."
      fi
    done
  fi
  if confirm "Set both secrets on $GH_REPO now with gh secret set?"; then
    set_secret POSTHOG_CLI_API_KEY "$PERSONAL_KEY"
    set_secret POSTHOG_CLI_PROJECT_ID "$POSTHOG_PROJECT_ID"
  else
    SKIPPED+=("gh secret set POSTHOG_CLI_API_KEY --repo $GH_REPO   (paste the key when asked)")
    SKIPPED+=("gh secret set POSTHOG_CLI_PROJECT_ID --repo $GH_REPO --body $POSTHOG_PROJECT_ID")
  fi
  PERSONAL_KEY=""
  unset PERSONAL_KEY
  end_step CI_KEY "Personal API key for symbol upload, as GitHub secrets"
fi

# ── 8. The first insight ──────────────────────────────────────────────────
if begin_step INSIGHT "Insight: unique installs per version" 4 \
  "A Trends insight counting installs per parterre version. It needs events from #261."; then
  note "Events arrive only once a release with #261's usage statistics is out. Until then"
  note "'Application Opened' isn't in the event list: skip this step and come back."
  if confirm "Has PostHog received parterre's 'Application Opened' events yet?"; then
    open_url "$POSTHOG/insights"
    step "Click 'New insight'; it opens as Trends."
    step "For series A, pick the event 'Application Opened'."
    step "Change its 'Total count' to 'Unique users': each install ID counts once."
    step "'+ Add breakdown' by the event property \$app_version (search for app_version)."
    step "Set the date range to the last 90 days, grouped by week."
    step "Name it 'Unique installs per version' (the pencil by the name) and Save."
    printf '\n'
    step "For the weekly view, make another the same way with 'Weekly active users (WAU)'"
    say  "  grouped by day, named 'Weekly active installs per version', and Save."
    end_step INSIGHT "Insight: unique installs per version"
  else
    SKIPPED+=("Insight: unique installs per version (once #261 sends events)")
  fi
fi

finish
note "Progress and the public values are kept in $ENV_FILE."
printf '\n'

